### ISSUE TITLE
Inconsistency in nomenclature 

### ISSUE THREAD

**Issue by MaraAlexeev** [LudvigOlsen/cvms#14]
Thanks for a super cool package. 
I was working with `evaluate()` and `plot_confustion_matrix()` tonight, and I noticed some inconsistency in the arguments. It might be intentional for reasons I don't understand, but it might be useful to have either `target_col` OR `targets_col` (same with predictions) in both functions. 

```
`evaluate(
  data,
  target_col,
  prediction_cols,
  type)`

```
```
plot_confusion_matrix(
  conf_matrix,
  targets_col = "Target",
  predictions_col = "Prediction",
  counts_col = "N"
)

```

**Comment by LudvigOlsen** [comment]
Hi Mara,

Thanks for the feedback. I completely agree that this is inconsistent.
I believe, this stems from how the related arguments in `confusion_matrix()` are called `targets` and `predictions` (which makes sense as they take vectors). I developed `plot_confusion_matrix()` while also working on that function, so I've probably just added the `_col` here. 

I will consider whether this should be changed (would be a breaking change). Probably most users don't use those arguments in `plot_confusion_matrix()` as the defaults work with the confusion matrix object in `evaluate()`, so that would make a transition easier.

**Comment by LudvigOlsen** [comment]
I've changed it such that it is `target_col` and `prediction_col`.
