### ISSUE TITLE
Issues with the next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [LudvigOlsen/cvms#24]
Hi

We are preparing the next release of ggplot2 and our reverse dependency tests shows an issue with cvms. The issue revolves around the deprecation of turning off a guide with `guides(<aes> = FALSE)`. Internally the guide is set to `"none"` instead of `FALSE` which breaks this unit test

https://github.com/LudvigOlsen/cvms/blob/36f7f7b578ddfc6c7e2fb023f0bd9da207ecaccb/tests/testthat/test_plotting_functions.R#L340

since you can't use `!` on `"none"`

We plan to release ggplot2 next week

best
Thomas

**Comment by LudvigOlsen** [comment]
Hi Thomas,

Thanks for letting me know.

I do use ggplot2::guides(fill = FALSE) in my confusion matrix plot. Is
there a better way to do the same since you're deprecating it? Or does that
still work and it's just the tests that should be is.null(...) instead?

I've just updated cvms on CRAN yesterday, so it will probably be some days
before they'll allow me to upload with automatic (i.e. fast) checks. But I
assume it won't directly break my code if it's just a deprecation?

Best,
Ludvig

Den tir. 8. jun. 2021 kl. 10.04 skrev Thomas Lin Pedersen <
***@***.***>:

**Comment by thomasp85** [comment]
you can just set `guides(fill = "none")` for the same effect... Setting it to `FALSE` will continue to work for now but will throw a deprecation warning so it is something you want to fix in the next release cycle.

CRAN will probably get back to you at some point due to failing tests but you should be fine letting it sit for a week or two so you can take the release fast lane

**Comment by LudvigOlsen** [comment]
Thanks, I'll do that. Good luck on the release :)

tir. 8. jun. 2021 20.41 skrev Thomas Lin Pedersen ***@***.***

**Comment by LudvigOlsen** [comment]
This has been solved.
