### ISSUE TITLE
Feature request: Only show data in sub_col on confusion matrix plot

### ISSUE THREAD

**Issue by marie3003** [LudvigOlsen/cvms#34]
Hi,

thank you for the nice package. It is really easy to work with and there are many nice features included.

I'm trying to use the `plot_confusion_matrix()` function. However my counts differ a lot. Because of that, some small counts are not distinguishable in the color scheme. I fixed this with using logarithmic counts instead.
I was even able to show the original counts on the confusion matrix with the `sub_col` argument. However, I don't want to show the percentages, just the raw counts. When I set 'add_normalized' to false I can only show the logarithmic counts and not the original ones. It would be really nice to have the possibility to only show the values inside the `sub_col` argument on the plot.

Best,
Marie

**Comment by LudvigOlsen** [comment]
Hi Marie,

Very interesting use case. Log-scaled color intensities seems like a feature that should be build in for sure.

The `sub_col` argument is quite new so it's possible some improvements should happen to how it can be used. I will think about whether it should be possible to have it as the top text as well.

For now though, I've added the option to set the `intensity_by` argument to one of following:  `"log counts"`, `"log2 counts"`, `"log10 counts"`, `"arcsinh counts"`. I hope this solves your use case. Otherwise, please let me know :-)

The changes are available on the `dev` branch for now. Will likely make a new release soon as there are a few new changes I found when developing the new web-app for the function: https://huggingface.co/spaces/ludvigolsen/plot_confusion_matrix

You can install the dev version with:

```r
devtools::install_github("ludvigolsen/cvms", ref = "dev")
```

**Comment by marie3003** [comment]
Hi Ludvig,

thank you so much for adding these options and for the fast reply! This worked for me. 

Best,
Marie

**Comment by LudvigOlsen** [comment]
That's great! Feel free to ask for more cool ideas when you get them :-)

Best,
Ludvig
